# Generated by Django 5.1.5 on 2025-04-19 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrituras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('user_sender', models.CharField(blank=True, max_length=255, null=True)),
                ('user_receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('id_escritura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escrituras.escritura')),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
    ]
