# Generated by Django 5.1.5 on 2025-04-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='notificacion',
            #name='mensaje',
            #field=models.CharField(blank=True, max_length=255, null=True),
        #),
    ]
