# Generated by Django 5.1.5 on 2025-04-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('proceso_id', models.AutoField(primary_key=True, serialize=False)),
                ('seriado_proceso', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('limite_tiempo', models.IntegerField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proceso',
                'managed': True,
            },
        ),
    ]
