# Generated by Django 5.1.5 on 2025-04-19 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritura',
            fields=[
                ('numero_escritura', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_notaria', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_otorgamiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_movimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_predio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_smart_contract', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_temporal_data', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_temporal_data2', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula_catastral', models.CharField(blank=True, max_length=255, null=True)),
                ('proceso_escritura', models.ForeignKey(db_column='proceso_escritura', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='procesos.proceso')),
            ],
            options={
                'db_table': 'escritura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolesVerificadores',
            fields=[
                ('id_registro_validadores', models.AutoField(primary_key=True, serialize=False)),
                ('id_escribano', models.CharField(blank=True, max_length=255, null=True)),
                ('id_juez1', models.CharField(blank=True, max_length=255, null=True)),
                ('id_notario', models.CharField(blank=True, max_length=255, null=True)),
                ('id_juez2', models.CharField(blank=True, max_length=255, null=True)),
                ('id_escritura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escrituras.escritura')),
            ],
            options={
                'db_table': 'roles_verificadores',
                'managed': True,
            },
        ),
    ]
