# Generated by Django 5.1.5 on 2025-02-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesVerificadores',
            fields=[
                ('id_registro_validadores', models.AutoField(primary_key=True, serialize=False)),
                ('id_escribano', models.CharField(blank=True, max_length=255, null=True)),
                ('id_juez1', models.CharField(blank=True, max_length=255, null=True)),
                ('id_notario', models.CharField(blank=True, max_length=255, null=True)),
                ('id_juez2', models.CharField(blank=True, max_length=255, null=True)),
                ('id_escritura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escrituras.escritura')),
            ],
            options={
                'db_table': 'roles_verificadores',
                'managed': True,
            },
        ),
    ]
