# Generated by Django 5.1.5 on 2025-02-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0002_rolesverificadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escritura',
            options={'managed': True},
        ),
    ]
