# Generated by Django 5.1.5 on 2025-02-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0003_alter_escritura_options'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritura',
            name='direccion_temporal_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        #migrations.AddField(
        #    model_name='escritura',
        #    name='proceso_escritura',
        #    field=models.ForeignKey(db_column='proceso_escritura', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='procesos.proceso'),
        #),
    ]
