# Generated by Django 5.1.5 on 2025-03-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0006_escritura_cedula_catastral_and_more'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='escritura',
        #    name='cedula_catastral',
        #    field=models.CharField(blank=True, max_length=255, null=True),
        #),
        #migrations.AddField(
        #    model_name='escritura',
        #    name='proceso_escritura',
        #    field=models.ForeignKey(db_column='proceso_escritura', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='procesos.proceso'),
        #),
    ]
