# Generated by Django 5.1.5 on 2025-04-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0007_escritura_cedula_catastral_and_more'),
    ]

    operations = [
    ]
