# Generated by Django 5.1.5 on 2025-03-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correcion',
            fields=[
                ('id_correcion', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.IntegerField()),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('is_resolved', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_notificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.notificacion')),
            ],
            options={
                'db_table': 'correccion',
                'managed': True,
            },
        ),
    ]
