# Generated by Django 5.1.5 on 2025-04-19 01:49

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escribano',
            fields=[
                ('escribano_id', models.AutoField(primary_key=True, serialize=False)),
                ('tribunal', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('notaria_asignada', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'escribano',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('juez_id', models.AutoField(primary_key=True, serialize=False)),
                ('tribunal', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_jurisdiccional', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'juez',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notario',
            fields=[
                ('notario_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_licencia', models.CharField(blank=True, max_length=255, null=True)),
                ('oficina_registro', models.CharField(max_length=255)),
                ('notaria_asignada', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'notario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('beneficiario_id', models.AutoField(primary_key=True, serialize=False)),
                ('municipio_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_poblacional', models.CharField(blank=True, max_length=255, null=True)),
                ('situacion_despojo', models.CharField(blank=True, max_length=255, null=True)),
                ('documentos_soporte', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beneficiario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hash_password', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_expedicion_cedula', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nt', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_permisos', to='auth.permission')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('usuario_rol_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': True,
            },
        ),
    ]
