# Generated by Django 5.1.5 on 2025-04-19 01:49

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [

 migrations.AddField(
            model_name='usuariorol',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.beneficiario'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='juez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.juez'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='escribano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.escribano'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='notario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.notario'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
