# Generated by Django 5.1.5 on 2025-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='correo_electronico',
        #),
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='numero_telefono',
        #),
        
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
