# Generated by Django 5.1.5 on 2025-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_correo_electronico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('beneficiario_id', models.AutoField(primary_key=True, serialize=False)),
                ('municipio_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_poblacional', models.CharField(blank=True, max_length=255, null=True)),
                ('situacion_despojo', models.CharField(blank=True, max_length=255, null=True)),
                ('documentos_soporte', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beneficiario',
                'managed': True,
            },
        ),
    ]
