# Generated by Django 5.1.5 on 2025-02-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_beneficiario'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='correo_electronico',
        #),
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='numero_telefono',
        #),
    ]
