# Generated by Django 5.1.5 on 2025-02-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'managed': True},
        ),
    ]
