# Generated by Django 5.1.5 on 2025-02-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuariorol_options'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='usuario',
         #   name='correo_electronico',
        #),
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='numero_telefono',
        #),
        migrations.AddField(
            model_name='usuariorol',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.beneficiario'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='escribano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.escribano'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='juez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.juez'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='notario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.notario'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
