# Generated by Django 5.1.5 on 2025-02-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_usuario_correo_electronico_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='correo_electronico',
        #),
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='numero_telefono',
        #),
    ]
