# Generated by Django 5.1.5 on 2025-03-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_usuario_managers_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='correo_electronico',
        #),
        #migrations.RemoveField(
        #    model_name='usuario',
        #    name='numero_telefono',
        #),
    ]
